language: node_js

services:
  - docker

node_js:
  - "12.14.1"
jobs:
  include:
    - stage: linting
      script: yarn lint
    - stage: publish
      if: branch = master
      script: yarn publish:docker
    - stage: deploy
      if: branch = master
      script: yarn deploy

after_success:
  - yarn codecov

notifications:
  email:
    recipients:
      - me@silverxu.com
    on_success: always
    on_failure: always
