language: node_js

services:
  - docker

node_js:
  - '12.14.1'
jobs:
  include:
    - stage: linting
      script: yarn build
    - stage: publish
      if: branch = master
      install: true
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn publish:docker
    - stage: deploy
      if: branch = master
      before_install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - pip install awsebcli --upgrade --user
      install: true
      script:
        - yarn deploy

after_success:
  - yarn codecov

notifications:
  email:
    recipients:
      - me@silverxu.com
    on_success: always
    on_failure: always
