service: covid-stats-dashboard

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager
  - serverless-offline

custom:
  serverless-nextjs: # <- add here
    assetsBucketName: 'covid-stats-assets-${self:provider.stage}'
  serverless-offline:
    httpPort: 3000
  customDomain:
    domainName: www.covidstats.com.au
    stage: prod
    basePath: ''
    certificateName: '*.covidstats.com.au'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: ${opt:stage}
  region: ap-southeast-2

package: # <- add here
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**

functions:
  api:
    handler: .next/serverless/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
