service: covid-stats

plugins:
  - serverless-finch

custom:
  hostedZoneName: covidstats.com.au
  aliasHostedZoneId: Z1WCIGYICN2BYD
  aliasDNSName: s3-website-ap-southeast-2.amazonaws.com
  siteName: www.covidstats.com.au
  client:
    bucketName: ${self:custom.siteName}
    distributionFolder: build
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: ${opt:stage}
  region: ap-southeast-2

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ['', ['arn:aws:s3:::', { 'Ref': 'StaticSite' }, '/*']]
    DnsRecord:
      Type: 'AWS::Route53::RecordSet'
      Properties:
        AliasTarget:
          DNSName: ${self:custom.aliasDNSName}
          HostedZoneId: ${self:custom.aliasHostedZoneId}
        HostedZoneName: ${self:custom.hostedZoneName}.
        Name: ${self:custom.siteName}
        Type: 'A'
